### ISSUE TITLE
TypeError: fixer() missing 1 required positional argument: 'check_hostname'

### ISSUE THREAD

**Issue by nschloe** [httplib2/httplib2#102]
I'm getting a funny exception when using [Debian's reportbug](https://packages.debian.org/sid/reportbug) that traces back to httplib2:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reportbug/ui/gtk2_ui.py", line 1049, in sync_pre_operation
    http_proxy=http_proxy, archived=archived, source=source)
  File "/usr/lib/python3/dist-packages/reportbug/debbugs.py", line 1073, in get_reports
    bugs = debianbts.get_bugs(pkg_filter, package)
  File "/home/nschloe/.local/lib/python3.6/site-packages/debianbts/debianbts.py", line 410, in get_bugs
    reply = soap_client.call('get_bugs', method_el)
  File "/home/nschloe/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 256, in call
    self.xml_response = self.send(method, self.xml_request)
  File "/home/nschloe/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 318, in send
    location, http_method, body=xml, headers=headers)
  File "/home/nschloe/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1396, in request
    self.disable_ssl_certificate_validation)
  File "/home/nschloe/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 979, in __init__
    timeout=timeout, context=context)
TypeError: fixer() missing 1 required positional argument: 'check_hostname'
```
The exception is triggerd by https://github.com/pysimplesoap/pysimplesoap/blob/master/pysimplesoap/transport.py#L72. Was there perhaps an API change in httpslib2 recently that pysimplesoap hasn't caught with yet?

**Comment by temoto** [comment]
`fixer` shadows Python stdlib `http.client.HTTPSConnection.__init__`. See https://docs.python.org/3/library/http.client.html

> The check_hostname parameter is also deprecated; the ssl.SSLContext.check_hostname attribute of context should be used instead.

So, proper answer is: there was API change in CPython stdlib that pysimplesoap hasn't caught with yet.

**Comment by nschloe** [comment]
Alright, moved the bug to https://github.com/pysimplesoap/pysimplesoap/issues/162. Thanks for the quick reply!

**Comment by nschloe** [comment]
Okay so, it seems that pysimplesoap won't incorporate the change; no activity there in many months.
