### ISSUE TITLE
TypeError: fixer() missing 1 required positional argument: 'check_hostname'

### ISSUE THREAD

**Issue by id8216** [httplib2/httplib2#126]
I change python version from 3.5 to 3.6 and got a problem with Google API authorization.
`Traceback (most recent call last):
  File "/home/ivan/Projects/pr_pmf/pr_pmf/pr_pmf/apps/core/tasks.py", line 33, in update_input_columns
    update_google_input_columns(user)
  File "/home/ivan/Projects/pr_pmf/pr_pmf/pr_pmf/apps/core/utils.py", line 25, in update_google_input_columns
    google_sheet = GoogleSheets(google_link)
  File "/home/ivan/Projects/pr_pmf/pr_pmf/pr_pmf/apps/tools/google_wrapper/wrapper.py", line 29, in __init__
    self.service = self.__service_by_user_secret()
  File "/home/ivan/Projects/pr_pmf/pr_pmf/pr_pmf/apps/tools/google_wrapper/wrapper.py", line 263, in __service_by_user_secret
    discoveryServiceUrl=self.DISCOVERY_URL)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/googleapiclient/discovery.py", line 222, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/googleapiclient/discovery.py", line 272, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/httplib2/__init__.py", line 1761, in request
    disable_ssl_certificate_validation=self.disable_ssl_certificate_validation,
  File "/home/ivan/Projects/pr_pmf/pr_pmf_env36/lib/python3.6/site-packages/httplib2/__init__.py", line 1247, in __init__
    context=context
TypeError: fixer() missing 1 required positional argument: 'check_hostname'`

httplib2 version: 0.12.0
oauth2client version: 4.1.3 

When I try to add string 
`check_hostname=None`
in file lib/python3.6/site-packages/httplib2/__init__.py everything worked fine.
![image](https://user-images.githubusercontent.com/17934965/50450446-c9cc3c80-0936-11e9-88c6-1eface5c5aae.png)

Please advise what do i do in my project so as not to get this error. 
Or maybe it will be fixed in the next version httplib2?

**Comment by temoto** [comment]
This is very strange, because doc says signature did not change with respect to `check_hostname`, if anything, this argument became obsolete in 3.6.

`python -V` please

**Comment by id8216** [comment]
Python 3.6.7

**Comment by temoto** [comment]
Looks like for all httplib2 supported (3.3-3.7) Python3 versions, `check_hostname` kwarg is defined so it should not hurt to add it. Trying patch now.

**Comment by temoto** [comment]
@id8216 to answer your direct question: of course it will be fixed in httplib2. For your project my advice is "vendor-patch" (copy httplib2 source, apply your patch, temporarily change project requirements to local patched version).

**Comment by id8216** [comment]
Thank you for answer.

**Comment by temoto** [comment]
Please search `def fixer(` in your virtualenv and project and show it's code.

**Comment by id8216** [comment]
python3.6/site-packages/pysimplesoap/transport.py

```
try:
    import httplib2
    if sys.version > '3' and httplib2.__version__ <= "0.7.7":
        import http.client
        # httplib2 workaround: check_hostname needs a SSL context with either 
        #                      CERT_OPTIONAL or CERT_REQUIRED
        # see https://code.google.com/p/httplib2/issues/detail?id=173
        orig__init__ = http.client.HTTPSConnection.__init__ 
        def fixer(self, host, port, key_file, cert_file, timeout, context,
                        check_hostname, *args, **kwargs):
            chk = kwargs.get('disable_ssl_certificate_validation', True) ^ True
            orig__init__(self, host, port=port, key_file=key_file,
                cert_file=cert_file, timeout=timeout, context=context,
                check_hostname=chk)
        http.client.HTTPSConnection.__init__ = fixer
except ImportError:
    TIMEOUT = None  # timeout not supported by urllib2
    pass
else:
    class Httplib2Transport(httplib2.Http, TransportBase):
```
But why pysimplesoap? it was not shown in traceback.
When I deactivated part of project that used pysimplesoap and deleted pysimplesoap from virtualenv (pip uninstall pysimplesoap) google api authorization worked fine. 
But why does it affect to google api authorization? 
That part of the project that used pysimplesoap was inactive during google api authorization.

**Comment by temoto** [comment]
I'm sorry, new resolution here - won't fix, because it's a bad idea to add workaround for a workaround for a problem that was fixed properly.

Please tell pysimplesoap that versions strings comparison only properly works for equality operators. `(0, 12) > (0, 7)` but `"0.12" < "0.7"

Proper solution is likely to remove that `fixer` altogether. I'm pretty sure we do correct with context and check_hostname now.

If they still want to leave fixer to support code that needs old httplib2 for some reason, the next best option is to parse version string. It could be as simple as:

```
def try_int(x):
  try:
    return int(x)
  except Exception:
    return x

def parse_version_loose(s):
  return tuple(map(try_int, s.split('.')))

if sys.version_info >= (3,) and parse_version_loose(httplib2.__version__) <= (0, 7, 7):
```

P.S.: it affects everything using stdlib http client because they override it with `http.client.HTTPSConnection.__init__ = fixer`
You can get confusing tracebacks when patching stuff like that. Sorry, I can't explain better.
We're lucky traceback even mentions `fixer` name.
