### ISSUE TITLE
email.FeedParser import error (has been renamed to email.feedparser)

### ISSUE THREAD

**Issue by limburgher** [httplib2/httplib2#164]
In python 3.8.2 email.FeedParser has been renamed to email.feedparser making "import httplib2" fail.

**Comment by limburgher** [comment]
Also email.message.

**Comment by limburgher** [comment]
Also email.utils. It also imports httplib which is no longer present.

**Comment by temoto** [comment]
Thanks.

**Comment by hroncok** [comment]
The imports mentioned here are all in the python2 folder, not python3. As said in https://bugzilla.redhat.com/show_bug.cgi?id=1830222 -- I believe this is a Fedora packaging error, as the python2 implementation gets installed for Python 3.

**Comment by temoto** [comment]
@limburgher can you show how to reproduce this issue starting with clean virtualenv?

**Comment by hroncok** [comment]
This was fixed in Fedora by fixing the packaging problem.

It might be replicated by installing to python2 and python3 form the same source dir I guess. Will try.

**Comment by hroncok** [comment]
```
[httplib2 (master)]$ python3 -m venv __venv3__
[httplib2 (master)]$ virtualenv -p python2.7 __venv2__

[httplib2 (master)]$ __venv2__/bin/python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/httplib2
copying python2/httplib2/iri2uri.py -> build/lib/httplib2
copying python2/httplib2/__init__.py -> build/lib/httplib2
copying python2/httplib2/socks.py -> build/lib/httplib2
copying python2/httplib2/certs.py -> build/lib/httplib2
copying python2/httplib2/cacerts.txt -> build/lib/httplib2

[httplib2 (master)]$ __venv3__/bin/python setup.py build
running build
running build_py

[httplib2 (master)]$ __venv2__/bin/python setup.py install --skip-build
...

[httplib2 (master)]$ __venv3__/bin/python setup.py install --skip-build
...

[httplib2 (master)]$ diff __venv*__/lib/python*/site-packages/httplib2-0.17.3-py*.egg/httplib2/iri2uri.py
[httplib2 (master)]$ diff __venv*__/lib/python*/site-packages/httplib2-0.17.3-py*.egg/httplib2/socks.py
[httplib2 (master)]$ diff __venv*__/lib/python*/site-packages/httplib2-0.17.3-py*.egg/httplib2/__init__.py
[httplib2 (master)]$ diff __venv*__/lib/python*/site-packages/httplib2-0.17.3-py*.egg/httplib2/certs.py

[httplib2 (master)]$ __venv3__/bin/python -c 'import httplib2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/churchyard/Dokumenty/RedHat/httplib2/__venv3__/lib64/python3.8/site-packages/httplib2-0.17.3-py3.8.egg/httplib2/__init__.py", line 28, in <module>
    import email.FeedParser
ModuleNotFoundError: No module named 'email.FeedParser'
```

**Comment by limburgher** [comment]
@hroncok is correct. Closing.
