### ISSUE TITLE
httplib2 fails when fips mode is enabled

### ISSUE THREAD

**Issue by mattfirtion** [httplib2/httplib2#17]
When trying to use the httplib2 module on a RHEL server is fips_enabled = 1, the module fails.  _cnonce uses the md5 algorithm which is not FIPS approved.

RHEL 6.7
httplib2 0.7.7

**Comment by stinky2nine** [comment]
Have you tried the latest release?

**Comment by mattfirtion** [comment]
I've not tried it with the latest release, but I do not see where that function has changed.  In my case, httplib2 is getting called from Ansible 1.9.  This works on environments where the os is not FIPS enabled -- same versions of httplib2, OS, Python, and Ansible.

Error:
```
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1469104841.43-141378045411033/uri", line 2082, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1469104841.43-141378045411033/uri", line 417, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout, validate_certs)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1469104841.43-141378045411033/uri", line 312, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1605, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1363, in _request
    authorization.request(method, request_uri, headers, body)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 524, in request
    self.challenge['cnonce'] = cnonce or _cnonce()
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 443, in _cnonce
    dig = _md5("%s:%s" % (time.ctime(), ["0123456789"[random.randrange(0, 9)] for i in range(20)])).hexdigest()
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```
