### ISSUE TITLE
Fail to validate HTTPS server while using custom CA file

### ISSUE THREAD

**Issue by drmalex07** [httplib2/httplib2#2]
Hello httplib2.
I am using httplib2==0.9.2.

My use case is quite simple: we have a private network and have setup some HTTPS services. These services provide certificates signed by a site-local CA authority. All certificates are signed using SHA-256 as signing algorithm.

Take that: 
- a self-signed root CA certificate exists inside `/etc/ssl/certs/ca-certificates.crt`  (the standard debian location)
- the certificate for CN `foo.localdomain` is signed by this local authority, and is installed to a web server https://foo.localdomain

I'am trying to use httplib2 to communicate with this service: 

``` python
h = httplib2.Http(ca_certs='/etc/ssl/certs/ca-certificates.crt')
resp, cont = h.request('https://foo.localdomain')
```

The above fails to perform a proper handshake, but unfortunately it returns poor feedback on where the actual problem is:

```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    resp, cont = h.request('https://foo.localdomain')
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/home/malex/pyenv/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

At the same time, the following `s_client` test succeeds (certificate verification returns `0`):

```
openssl s_client -connect foo.localdomain:443 -servername foo.localdomain -CAfile /etc/ssl/certs/ca-certificates.crt
```

Also, `curl` succeeds:

```
curl --cacert /etc/ssl/certs/ca-certificates.crt https://foo.localdomain
```

**Comment by stinky2nine** [comment]
Which platform and version? If Linux, which distribution?

**Comment by drmalex07** [comment]
On Debian Linux 8.2, kernel  3.16.0

**Comment by stinky2nine** [comment]
Just to be sure (and after checking https://wiki.debian.org/Python), you are using default packages from the distribution? Including Python 2.7 and httplib2?

Can you do a quick test in Python console?

```python
import socket
import ssl

context = ssl.create_default_context()
context.verify_mode = ssl.CERT_REQUIRED
context.check_hostname = True
context.load_verify_locations('/etc/ssl/certs/ca-certificates.crt')

conn = context.wrap_socket(socket.socket(socket.AF_INET), server_hostname='foo.localdomain')
conn.connect(('foo.localdomain', 443))
```

**Comment by drmalex07** [comment]
No, i am not using the distribution's packages, i am using the default packages from PyPi. 

My environment (`pip freeze`) is:
```
argparse==1.2.1
httplib2==0.9.2
wsgiref==0.1.2
```

The test you have suggested (on plain sockets), succeeds and no error is reported. As i mentioned before, common HTTP clients such as curl/wget, as long as OpenSSL's testing client also succeed.

Can't you reproduce the error, if you create a fresh virtual environment?

**Comment by stinky2nine** [comment]
httplib2 doesn't have a testing farm. Everything is tested manually and depends on the contributor's environment, test results can be varied. Given that we are just volunteers, we do the best we can. So to answer your questions, no, I can't replicate the issue. You will have to help us or this issue will probably just go to the backlog forever.

https://github.com/httplib2/httplib2/blob/master/python2/ssl_protocol_test.py has some coverage on SSL cert validation and it works on Ubuntu 12.04 LTS as well as webOS w/ homebrew.

**Comment by drmalex07** [comment]
Do you think i should fork and add some test cases (e.g. communicating a server using a site-wide valid certificate)? 

If i understood well, you have 2 testing environments (Ubuntu 12.04, webOS) and you assume that all Python packages are pulled from the OS-default repositories (?).

**Comment by stinky2nine** [comment]
The problem with Linux is that there are so many distributions out there. Each one comes with a slightly different version of OpenSSL and python2/3, whether patched or not-patched. Ubuntu 14.04 (sorry I gave the wrong version on my last post) and 16.04 for example are Long Term Support (LTS) version which will continue to receive security updates for 3 years on desktop and 5 years on server edition.

You should be able to copy or modify this test case https://github.com/httplib2/httplib2/blob/master/python2/ssl_protocol_test.py#L22 to replicate the issue your are seeing on your environment. Let me know if you can replicate the issue against httplib2 HEAD.

**Comment by galvez** [comment]
@drmalex07 Just thought I'd ask if you managed to sort this out. Did you?

**Comment by drmalex07** [comment]
No, i did not

**Comment by galvez** [comment]
@drmalex07 Alright, reopened the issue -- I've added to my queue, going through a bunch of unresolved issues and pull requests. Should spend the next couple weeks doing my best to clean things up around here.

**Comment by abergmeier** [comment]
Same here.

**Comment by marcvs** [comment]
I ran into the same error with the debian shipped python3-httplib2 0.9.2+dfsg-1

I found this fixed to work in httplib2-0.11.3 from pypi using a virtualenv

**Comment by trourance** [comment]
I faced the same issue using flask-oidc which is using httplib2 (see puiterwijk/flask-oidc#52). The only way I found to fix that issue was to add the custom certificate in the cacerts.txt file.
`cat mycacert.crt >> cacerts.txt`

**Comment by dineiar** [comment]
Seems to be true @gertvdijk, I just get through the error using the `disable_ssl_certificate_validation` option of httplib2 (see [jay0lee/GAM/#676](https://github.com/jay0lee/GAM/issues/676) for more info). It is not the best solution to ignore the SSL certificates, as this opens a door for man-in-the-middle attacks, but it put this to work.

**Comment by gertvdijk** [comment]
It's worth noting that release v0.12.0 of httplib2, it became much smarter ([`cert.py`](https://github.com/httplib2/httplib2/blob/v0.12.0/python2/httplib2/certs.py), via PR #117):

* it loads a custom CA bundle specified by the environment variable HTTPLIB2_CA_CERTS <br> <sup>(other Bazel users: this should be set by Bazel's '--action_env' build parameter)</sup>
* if not given, the former extension using httplib2 ca_certs_locater is requested for a system CA bundle 
* if this package is not installed, it loads the bundle from the Python library 'certifi' if available <br> *(note: Debian/Ubuntu has patched this to return the system CA bundle instead of the vanilla Mozilla bundle)*
* as fallback, uses its own bundled file with a CA bundle.

**Comment by 1oglop1** [comment]
@gertvdijk Did the #117 fix this error https://travis-ci.org/jans-forks/vcrpy/jobs/491864771#L834
```
server hit an exception serving request: EOF occurred in violation of protocol (_ssl.c:1748)
```

**Comment by gertvdijk** [comment]
@1oglop1 (I have no clue what kind of project you just pointed me at, this is a general answer after looking 1 minute at that traceback.)

> ssl.CertificateError: hostname '127.0.0.1' doesn't match 'localhost'

Is a totally unrelated error.

**Comment by 1oglop1** [comment]
Thanks, that was kind of an effort and answer I wanted. I just did not want to dive into something what is already solved.
