### ISSUE TITLE
[PATCH] patch attached to fix problem => ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by bughunter2** [httplib2/httplib2#244]
The attached patch fixes a problem that occurs in newer Python versions.

The problem is that `check_hostname` is `True` at the moment an `SSLContext` is created. It must first be set to `False`, before attempting to set `verify_mode` to `ssl.CERT_NONE`.

The attached patch fixes the problem:

```
diff -ur original/__init__.py fixed/__init__.py
--- original/__init__.py	2024-08-01 21:46:05.880473168 +0200
+++ fixed/__init__.py	2024-08-01 21:46:05.880473168 +0200
@@ -152,6 +152,13 @@
         raise RuntimeError("httplib2 requires Python 3.2+ for ssl.SSLContext")
 
     context = ssl.SSLContext(DEFAULT_TLS_VERSION)
+
+    # check_hostname requires python 3.4+
+    # we will perform the equivalent in HTTPSConnectionWithTimeout.connect() by calling ssl.match_hostname
+    # if check_hostname is not supported.
+    if hasattr(context, "check_hostname"):
+        context.check_hostname = not disable_ssl_certificate_validation
+
     context.verify_mode = ssl.CERT_NONE if disable_ssl_certificate_validation else ssl.CERT_REQUIRED
 
     # SSLContext.maximum_version and SSLContext.minimum_version are python 3.7+.
@@ -170,11 +177,6 @@
             context.minimum_version = minimum_version
         else:
             raise RuntimeError("setting tls_minimum_version requires Python 3.7 and OpenSSL 1.1 or newer")
-    # check_hostname requires python 3.4+
-    # we will perform the equivalent in HTTPSConnectionWithTimeout.connect() by calling ssl.match_hostname
-    # if check_hostname is not supported.
-    if hasattr(context, "check_hostname"):
-        context.check_hostname = not disable_ssl_certificate_validation
 
     context.load_verify_locations(ca_certs)
 ```

And this demonstrates the problem:

```
$ python3
...
>>> import ssl
>>> c = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
>>> c.verify_mode = ssl.CERT_NONE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/ssl.py", line 680, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.
```

Changing the order of the code fixes the problem:

```
$ python3
...
>>> import ssl
>>> c = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
>>> c.check_hostname = False
>>> c.verify_mode = ssl.CERT_NONE
>>> quit()
```

Version info:
```
$ rpm -qf /usr/lib/python3.12/site-packages/httplib2
python3-httplib2-0.21.0-6.fc40.noarch

```

**Comment by bughunter2** [comment]
As I was writing this I saw it's already fixed in httplib2.
Submitted anyway for documentative purposes if others stumble upon it.
Cheers.
