### ISSUE TITLE
SyntaxError (Python 2 style 'print') in Python 3 (v0.10.1 from PyPI)

### ISSUE THREAD

**Issue by spiow** [httplib2/httplib2#43]
```
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import httplib2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/venv/lib/python3.4/site-packages/httplib2/__init__.py", line 932
    print "connect: (%s, %s) ************" % (self.host, self.port)
                                         ^
SyntaxError: invalid syntax
>>> 
```
Looks like Python 2 code was uploaded to PyPI for Python3.

**Comment by temoto** [comment]
Thanks, fixing now.

**Comment by temoto** [comment]
Wrong wheel was removed from 0.10.1 version, so clean pip cache + reinstall should work.
If that's not a preferable option, use 0.10.2, it doesn't contain wheels at all.

I'm sorry guys, wanted to move forward and provide wheels, but didn't check them upfront.
