### ISSUE TITLE
http proxy raise 403 error

### ISSUE THREAD

**Issue by liketic** [httplib2/httplib2#59]
Hi, 

I got 403 forbidden error when I send a request over proxy, this is my code:
```python
proxy_info = ProxyInfo(proxy_type=socks.PROXY_TYPE_HTTP,
                                       proxy_host='my host',
                                       proxy_port='my port',
                                       proxy_username='my proxy username',
                                       proxy_password='my proxy password',
                                       proxy_rdns=False)
http = Http(proxy_info=proxy_info)
response, content = http.request(url, method, headers=headers)
```
Then I got a exception:
```python
Traceback (most recent call last):
  File "/Users/likel/httplib2test/main.py", line 141, in send_request
    response, content = http.request(url, method, headers=headers)
  File "/Users/likel/httplib2test/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/likel/httplib2test/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/likel/httplib2test/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/Users/likel/httplib2test/httplib2/__init__.py", line 1033, in connect
    sock.connect((self.host, self.port))
  File "/Users/likel/httplib2test/httplib2/socks.py", line 424, in connect
    self.__negotiatehttp(destpair[0], destpair[1])
  File "/Users/likel/httplib2test/httplib2/socks.py", line 390, in __negotiatehttp
    raise HTTPError((statuscode, statusline[2]))
HTTPError: (403, 'Forbidden')
```
I'm sure the REST service didn't respond 403 because I can get correct result when I use curl or requests lib. I don't know the root cause here and also not sure if this is a bug in httplib2. Thanks in advance.

**Comment by temoto** [comment]
Let's compare bytes on wire to proxy for httplib2 and curl/requests.
Use strace/tcpdump/wireshark to watch what's actually going into network. For curl, `curl -vo/dev/null` is enough.
