### ISSUE TITLE
httplib2 + gevent = ConcurrentObjectUseError?

### ISSUE THREAD

**Issue by mayli** [httplib2/httplib2#66]
Hi, I was using googleapiclient + gevent, and hit the following bug. It seems httplib2 is calculating `conn_key` by  [this line](https://github.com/httplib2/httplib2/blob/master/python2/httplib2/__init__.py#L1516), it doesn't care about the greenlet, however greenlet doesn't like share a connection with each other. So, I am proposing using this method to compute `conn_key`:

`conn_key = ":".join([threading.current_thread().name, scheme, authority])`

My script works well with the above patch, the only thing that makes me concerned is this bug doesn't happen on regular python interpreter and the patch will prevent regular threads sharing connections. Any advice?

Full stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "test.py", line 166, in test
    request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 894, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 621, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1307, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 458, in recv
    return self.read(buflen)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 318, in read
    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 176, in _wait
    raise _socketcommon.ConcurrentObjectUseError('This socket is already used by another greenlet: %r' % (watcher.callback, ))
ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x7f3b37050910>>
```

**Comment by temoto** [comment]
This patch also prevents green threads from sharing connections if threading module was patched to be green friendly.

I think your best option is lock dictionary.

```
locks = {}

@contextlib.contextmanager
def limit(key):
  with locks.setdefault(key, threading.Lock()):
    yield


def somewhere():
  conn_key = scheme+authority  # sorry you have to copy this code from httplib2, it must return same key
  with limit(conn_key):
    http.request(...)
```

**Comment by mayli** [comment]
The above patch will force the use to **share** the connection, even he is trying to use multi-thread, which in most cases he wants to make multiple connections.
Could we make a flag in __init__ to toggle this behavior on/off? This could be useful in scenarios that user wants to disable sharing between threads. (eg. better concurrency, gevent)

**Comment by temoto** [comment]
@mayli you are right. Here's what I've done for my crawler in 2010 https://github.com/temoto/heroshi/blob/ff3561a5c30d6ebb48b7148cec1f70fce4539812/heroshi/worker/Crawler.py a pool of `httplib2.Http` objects, basically avoid internal connection pool in httplib2, same as what you said in last message.

We should probably work to make httplib2 connection pool better.

Seems disabling connection pool could be useful option, yes.

**Comment by mayli** [comment]
@temoto I got those two possible approaches for this issue
1. have a toggle in `__init__` to enable/disable sharing between threads
2. provide a optional kwarg to customize the computing of `conn_key`, eg `conn_key_func=None`

approach 1 is easier and could fit most use cases (at least works for me)
approach 2 is more flexible and could also be implemented as an extra method to override (more oop), but this will introduce an extra function all per requests (more cpu cycles slightly)

**Comment by temoto** [comment]
You can't do a better `conn_key` really. Either you want to reuse connections or not. Separate connection per thread is just wrong.

**Comment by mayli** [comment]
@temoto why "Connection to each domain per thread is just wrong."?

**Comment by temoto** [comment]
@mayli I'm sorry for strong language. I don't know design of your application, it may be OK considering how you use threads. In general case we can't include it in httplib2 because almost always it will be used in wrong way.

Problems:

* **prevents connection reuse** - you start a thread and make request which opens new connection, later you start new thread and make request to same server, but now it must open new connection instead of using existing idle one
* easy to overwhelm remote servers with excess concurrent requests causing DoS for them and IP blacklist for you
* hard to reason how much local resources your program is consuming

As of 2017-08 `httplib2.Http` object promise to have at most 1 outgoing connection to each network location (scheme:host:port). So developer is able to control number of connections per remote server (prevent DoS) and overall outgoing connections (to account local resources). With connection pool per thread you basically multiple those numbers by number of threads. With green threads usually there is either no thread limit or it's very high, thus you get outgoing connections out of control.

**Comment by mayli** [comment]
@temoto it's sort of solving a problem that doesn't exist. so, first, httplib2's connection pool is broken on gevent. And there is no way to disable connection pooling without hacking into httplib2.
There are tons of libs (even the default urllib/urllib2, and the human's requests) don't do this pooling by default, why httplib2 must provide this to prevent DoS?

> prevents connection reuse - you start a thread and make request which opens new connection, later you start new thread and make request to same server, but now it must open new connection instead of using existing idle one
It's not prevents, it's customize how connection is shared. Instead have one connection shared by all possible threads, `conn_key` can be used to control the concurrency level. One per thread in my case, or a fixed number of concurrent connections by more fancy `conn_key_func`.

> easy to overwhelm remote servers with excess concurrent requests causing DoS for them and IP blacklist for you
Why do we care about this when designing an optional functionality in a library? I didn't say make this the default behavior, and I am proposing to provide a way to enable an alternative behavior.
What if someone is using httplib2 to write a http server benchmark tools?

> hard to reason how much local resources your program is consuming
Why, if we can override the `conn_key_func` method, and if it make the cache a ThreadLocal object, my program is just using cache  * number of threads of resources.

> As of 2017-08 httplib2.Http object promise to have at most 1 outgoing connection to each network location (scheme:host:port). 
Do you think it's a feature or a limitation/restriction? And it is documented anywhere except written in the code?

> With connection pool per thread you basically multiple those numbers by number of threads.
Yes, and it's intended by the developer. Is there any other http library enforcing this restriction without an option to turn it off? 

There are good [examples ](https://github.com/shazow/urllib3/blob/master/urllib3/connectionpool.py#L98) of the implementation of connection pools, and I think httplib2's is way too _simplified_ and non-gevent-thread-safe.

And speaking of _simplified_, there are at least two disadvantages besides the gevent thing:
 
- hard to reason how much local resources your program is consuming
Yes, its' a disadvantage of current implementation.
Since there is no `ttl`, `max_entry` or other method to tracking/limit the cache, and the `httplib2.Http` will keep all connections in cache forever in memory. Which leads memory issues if the client is accessing random sites and only access once.
- the current connection cache doesn't validate if the connection is still alive
If a program sends two requests and a long sleep in between, the seconds one will likely pickup the stale conn and fail since most http servers will cut the connection if no activity is detected for a certain period.

I believe those are not the common use case of httplib2, but it seems it's really hard to customize the cache behavior when you really needs them. I hope there is a method to override, or a cache object to pass as parameter of `__init__` to let developers to provide more advanced connection pools.

**Comment by temoto** [comment]
Most important: yes, current connection pool is far from perfect. Yes, we should provide ways to customise idle connection pool. Exposing `conn_key` is not one of those ways.

* On comparison with other libraries: `httplib2.Http == requests.Session`. You don't have to create and hold one `Http` object. Please treat all global variables with great care.
* For benchmarking tool and other perfectly valid cases: use more than one `Http` object.
* For ttl, managing cache memory, turning pool off: delete `Http` object.
* On idle connections reuse: it should just work. If you send a request, wait enough for server to close idle connection then send another request - you should get a response as if there was no cache. If you encounter other behavior, please open issue, we will fix it.

As of today your best options:

* (green)thread synchronized pool of `Http` objects, see http://www.gevent.org/gevent.pool.html#gevent.pool.Pool http://eventlet.net/doc/modules/pools.html#eventlet.pools.Pool (you can copy eventlet code in your project)
* single `Http` object per (green)thread (which incidentally makes the same as your conn_key patch, plus better memory management)
